# Generated by Django 4.1.1 on 2022-10-21 14:41

import django.core.validators
from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=300,
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                upload_to="images",
                validators=[petstagram.photos.validators.validate_file_size],
            ),
        ),
    ]
